name: Java CI 

on:
  # push:
  #   branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    name: CI action
    runs-on: ubuntu-latest
   # container:
    #  image: lucasalt/act_base:latest

    steps:
      - uses: actions/checkout@v2
      - name: Build docker-compose stack
        run: |
          echo ---Building and starting up docker---
          docker-compose -f docker-compose.yml up -d --build
          echo ---Containers up---
      - name: Check running containers
        run: docker ps
     
      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.yml down
        
     #docker7
  docker:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v1
      - name: Docker Hub Sign-in
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Building Docker Image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_RUN_ID} .
      - name: Publish Docker Image
        run: docker push $REPO
